lastupdatecheck: 0
recentrepos:
- /Users/thomas-delalande/.dotfiles
- /Users/thomas-delalande/vgw/pok-poker
- /Users/thomas-delalande/vgw/gp-dashboard
- /Users/thomas-delalande/dev/msg-bot
- /Users/thomas-delalande/vgw/gp-game-client
- /Users/thomas-delalande/vgw/gp-poker
- /Users/thomas-delalande/vgw/gp-achievements
- /Users/thomas-delalande/vgw/gp-poker-site
- /Users/thomas-delalande/dev/.dotfiles
- /Users/thomas-delalande/vgw/pok-user
- /Users/thomas-delalande/vgw/pok-auth0
- /Users/thomas-delalande/vgw/pok-client-web
- /Users/thomas-delalande/vgw/pok-customer-due-diligence
- /Users/thomas-delalande/dev/leptos
- /Users/thomas-delalande/.raycast/extensions/tmux-sessionizer-raycast
- /Users/thomas-delalande/dev/leptos-tailwind-starter
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
