---
  - name: Ensure .config directory exists.
    file:
      dest: "{{ lookup('env', 'HOME') }}/.config"
      state: directory

  - name: Link dotfiles
    command: "ln -sfv {{ dotfiles_directory }}/{{ item }} {{ lookup('env', 'HOME') }}/.{{ item }}"
    loop: "{{ dotfiles_files }}"
