---
  - name: Ensure .ssh directory exists.
    file:
      dest: "{{ lookup('env', 'HOME') }}/.ssh"
      mode: 0700
      state: directory

  - name: Install ssh key
    copy:
      src: "{{ ssh_keys_directory }}/{{ item }}"
      dest: "{{ lookup('env', 'HOME') }}/.ssh/{{ item }}"
      mode: 0600
    loop: "{{ ssh_keys }}"

  - name: Install ssh key public
    copy:
      src: "{{ ssh_keys_directory }}/{{ item }}.pub"
      dest: "{{ lookup('env', 'HOME') }}/.ssh/{{ item }}.pub"
      mode: 0644
    loop: "{{ ssh_keys }}"

  - name: Install ssh config files
    copy:
      src: "{{ ssh_keys_directory }}/{{ item }}"
      dest: "{{ lookup('env', 'HOME') }}/.ssh/{{ item }}"
      mode: 0600
    loop: "{{ ssh_config_files }}"
