---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:
    - import_tasks: tasks/osx.yml
      tags: ['osx']
    - import_tasks: tasks/homebrew.yml
      tags: ['brew']
    - import_tasks: tasks/dotfiles.yml
      tags: ['dotfiles']
    - import_tasks: tasks/nvim.yml
      tags: ['nvim']
