---
- name: Configure host.
  hosts: all

  roles:
    - role: elliotweiser.osx-command-line-tools

  tasks:
    - import_tasks: tasks/osx.yml
      tags: ['osx']
    - import_tasks: tasks/homebrew.yml
      tags: ['brew']
    - import_tasks: tasks/dotfiles.yml
      tags: ['dotfiles']
    - import_tasks: tasks/nvim.yml
      tags: ['nvim']
    - import_tasks: tasks/ssh.yml
      tags: ['ssh']
